Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/WordArray:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  Exclude:
  - lib/game.rb
  - lib/game_looper.rb
Metrics/BlockLength:
  Exclude:
  - spec/*
Metrics/MethodLength:
  Exclude:
  - spec/display_spec.rb
Metrics/ParameterLists:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - Guardfile